version: '3.4'

services:
  calculatesinterest.api:
    container_name: calculatesinterest
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:80"
    networks:
      - my-network
networks:
  my-network:
      external: true